server {
  listen 443 ssl http2;
  server_name test.mgt.com;
  root /var/www/magento/pub;
  
  ssl_certificate /etc/nginx/ssl/test.mgt.com.crt;
  ssl_certificate_key /etc/nginx/ssl/test.mgt.com.key;
  
  index index.php;
  
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }
  
  location ~ \.php$ {
    fastcgi_pass unix:/run/php/php8.3-test-ssh.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
}
