[test-ssh]
user = test-ssh
group = clp
listen = /run/php/php8.3-test-ssh.sock
listen.owner = test-ssh
listen.group = clp
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
chdir = /var/www/magento
